version: '3.4'

services:
  nodejs_mongo_docker:
    image: nodejs_mongo_docker
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/code
      - node_modules:/node_modules
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

volumes:
  data:
  node_modules: